assignment/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.IndexView.as_view(),name='index'),
    path('course/',include(('assignment_info.urls', 'assignment_info'), namespace='assignment_info')),
    path('accounts/', include('allauth.urls')),
    # path('accounts/',include('accounts.urls')),
    # path('accounts/',include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

assignment_info/urls.py
from django.urls import path
from . import views


app_name='assignments'

urlpatterns=[
    path('', views.AssigmentList,name='list'),
    path('grading_page/<int:pk>', views.GradingPage,name='grading_page'),
    # path('after_grading/<int:pk>', views.AfterGrading,name='after_grading'),
    path('submit/<int:pk>/', views.SubmissionFormView,name='submit'),
    path('register_course/<int:pk>/', views.RegisterFormView,name='register_course'),
    path('create_assignment/', views.CourseView, name='create'),
    path('create_course/', views.CreateCourseView, name='create_course'),
    path('submissions/',views.SubmissionListView,name='submission'),
    path('assignment/<int:pk>/',views.Assignments_list,name='assignment_list'),
    path('assignment/<int:pk>/delete/',views.deletingAssign,name='deleteassign'),
    path('available_courses/',views.AvailableListView,name='available'),
    path('deregister/<int:pk>/',views.DeregisterCourse,name='deregister_course'),

]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

  <title>Submissions Portal</title>
  <link rel = "icon" href ="{% static 'backend.png' %}" type = "image/x-icon"> 
  <link href="https://fonts.googleapis.com/css2?family=Merriweather+Sans:wght@500&display=swap" rel="stylesheet">

  <style>
    img {
      margin-top: -5px;
      margin-right: 12px;
    }
  </style>

</head>


<body>
  {% if messages %}
    <div class="container">
      {% for message in messages %}
        <div class="text-center border-bottom">{{message}}</div>
      {% endfor %}
    </div>
  {% endif %}


  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
    crossorigin="anonymous"></script>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <!-- <a class="navbar-brand" href="#">
      <img src="{% static 'IIT_Guwahati_Logo.png' %}" width="40" height="40">
    </a> -->

    <div class="container">
      <span class="navbar-brand mb-0 h1"  style="font-size: 2em;"> <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'IIT_Guwahati_Logo.png' %}" width="35" height="35">Submissions Portal</a></span>
      <ul class="nav justify-content-end">
        {% if user.is_authenticated %}
        <a class="nav-link active" href="" style="color: white;">{{ user.username }}</a>
        {% endif %}
        {% if user.is_staff %}
        <a class="nav-link active" href="{% url 'assignments:create_course' %}" style="color: white;">Create Course</a>
        <a class="nav-link active" href="{% url 'assignments:create' %}" style="color: white;">Create Assignment</a>
        {%endif%}
        {% if user.is_authenticated or user.is_staff %}
        <a class="nav-link active" href="{% url 'account_logout' %}" style="color: white;">Logout</a>
        {% else %}
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'account_login' %}" style="color: white;">Login</a>
        </li>
        {% endif %}

      </ul>
    </div>
  </nav>
  <div class='container'>

      {% block content %}

      {% endblock %}
  </div>
</body>

</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1 style="font-family: 'Merriweather Sans', sans-serif; text-align: center; margin-top: 0.7em; border: 2px solid black;padding-top: 0.2em; padding-bottom: 0.2em; border-radius: 5px; ">Assignment
    Submission Portal</h1>

{% if not user.is_authenticated %}
<br>
<center>
<div class="container" style="margin-top:0.7em;">
  <div class="container">
    <div class="row">
      <div class="col-sm">
        <div class="card " style="width: 18rem;border: 2px solid black;border-radius: 10px;">
          <div class="card-body">
            <h5 class="card-title" style="text-align: center;">Login</h5>

            <p class="card-text" style="font-family: 'Merriweather Sans';">Login to your account below</p>
            <div class="text-center">

              <a href="{% url 'account_login' %}" style="color: white;"><button type="button" class="btn btn-success">Login</button></a>
            </div>

          </div>
        </div>
      </div></center>
      <!-- <div class="col-sm">
        <div class="card " style="width: 18rem; border: 2px solid black; border-radius: 10px;">
          <div class="card-body">
            <h5 class="card-title" style="text-align: center;">Sign Up</h5>

            <p class="card-text" style="font-family: 'Merriweather Sans';">New to the portal? Sign up now!</p>
            <div class="text-center">


              <a href='{% url 'account_signup' %}'><button type="button" class="btn btn-success"> Sign up</button></a>
            </div>
            <br>

          </div>
        </div>
      </div> -->
      <!-- <div class="col-sm">
        <div class="card " style="width: 18rem; border: 2px solid black; border-radius: 10px;">
          <div class="card-body">
            <h5 class="card-title" style="text-align: center;">Admin Login</h5>

            <pre class="card-text" style="font-family: 'Merriweather Sans';">
            Are you an admin? Login now!
            </pre>
            <div class="text-center">

              <a href='{% url 'account_login' %}'><button type="button" class="btn btn-success">Login</button></a>
            </div>
          </div>
        </div>
      </div> -->
    </div>
  </div>
</div>
{% else %}
<div class="card text-center">
  <div class="card-header">
  </div>
  <div class="card-body">
    <h5 class="card-title">Offered Courses</h5>
    <a href="{% url "assignments:available" %}" class="btn btn-primary">Courses</a>
    <br><br>
    <h5 class="card-title">Assignment List</h5>
    <a href="{% url "assignments:list" %}" class="btn btn-primary">Assignments</a>
    {% if user.is_staff %}
    <br><br>
    <h5 class="card-title">Assignment Submissions</h5>
    <a href="{% url "assignments:submission" %}" class="btn btn-primary">Submissions</a>
    {% endif %}
  </div>
  <div class="card-footer text-muted">
  </div>
</div>
{% endif %}

{% endblock %}