assignment/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.IndexView.as_view(),name='index'),
    path('course/',include(('assignment_info.urls', 'assignment_info'), namespace='assignment_info')),
    path('accounts/', include('allauth.urls')),
    # path('accounts/',include('accounts.urls')),
    # path('accounts/',include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

assignment_info/urls.py
from django.urls import path
from . import views


app_name='assignments'

urlpatterns=[
    path('', views.AssigmentList,name='list'),
    path('grading_page/<int:pk>', views.GradingPage,name='grading_page'),
    # path('after_grading/<int:pk>', views.AfterGrading,name='after_grading'),
    path('submit/<int:pk>/', views.SubmissionFormView,name='submit'),
    path('register_course/<int:pk>/', views.RegisterFormView,name='register_course'),
    path('create_assignment/', views.CourseView, name='create'),
    path('create_course/', views.CreateCourseView, name='create_course'),
    path('submissions/',views.SubmissionListView,name='submission'),
    path('assignment/<int:pk>/',views.Assignments_list,name='assignment_list'),
    path('assignment/<int:pk>/delete/',views.deletingAssign,name='deleteassign'),
    path('available_courses/',views.AvailableListView,name='available'),
    path('deregister/<int:pk>/',views.DeregisterCourse,name='deregister_course'),

]

assignment_info/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

class Cname(models.Model):
    code = models.CharField(max_length=10, unique=True)
    course_name = models.CharField(max_length=30,default='Course Name')
    secret_code = models.CharField(max_length=30,default='Secret Code')

    def __str__(self):
        return self.code

class RegUsers(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,default=1)
    course=models.ForeignKey(Cname,on_delete=models.CASCADE,default=1,related_name='reg_users')

    def get_absolute_url(self):
        return reverse('assignments:list')

    def __str__(self):
        return "{}-{}".format(self.user.username,self.course.code)


class Course(models.Model):
    name=models.CharField(max_length=30,blank=False)
    code=models.ForeignKey(Cname,on_delete=models.CASCADE,default=1,related_name='course_code')
    question=models.TextField(blank=False)
    question_file=models.FileField(blank=True,null=True)
    deadline_date=models.DateField(null=True)
    deadline_time =models.TimeField(null=True)
    max_marks=models.IntegerField(default=10)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['name', 'code'], name='unique_course_name')
        ]

    def __str__(self):
        return "{}-{}".format(self.code,self.name)



class Submissions(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,default=1)
    course=models.ForeignKey(Course,on_delete=models.CASCADE,default=1,related_name='submission')
    answer=models.FileField(upload_to='assignments')
    submitted_at=models.DateTimeField(auto_now=True,blank=False)
    marks=models.IntegerField(default=-1)
    feedback=models.TextField(blank=True,default='No feedback')
    checked_by = models.CharField(max_length=30,blank=True,default='Not checked yet')


    def get_absolute_url(self):
        return reverse('assignments:list')

    def __str__(self):
        return "{}-{}".format(self.user.username,self.user.first_name+' '+self.user.last_name)

assignment_info/forms.py
from django import forms
from .models import Submissions,Course,Cname,RegUsers
# import self as self
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError



class CreateCourseForm(forms.ModelForm):
    code=forms.CharField(max_length=10)
    course_name=forms.CharField(max_length = 30)
    secret_code = forms.CharField(max_length=30)
    
    class Meta():
        model=Cname
        fields=('code','course_name','secret_code')


class CourseForm(forms.ModelForm):
    name=forms.CharField(max_length=100)
    # code=forms.CharField(max_length=100)
    code = forms.ModelChoiceField(queryset=Cname.objects.all())
    question=forms.CharField(widget=forms.Textarea, required=False)
    question_file=forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
    deadline_date=forms.DateField(widget=forms.SelectDateWidget)
    deadline_time=forms.TimeField()
    max_marks=forms.IntegerField()
    
    class Meta():
        model=Course
        fields=('name','code','question','deadline_date','deadline_time','max_marks','question_file')

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(CourseForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        date1 = RegUsers.objects.filter(course=cleaned_data['code'], user=self.user).exists()
        x = 0
        print(date1)
        if date1 == False:
            raise forms.ValidationError('User cannot create assignment for this course. First register for the course.')
        return cleaned_data

class SubmissionForm(forms.ModelForm):
    class Meta():
        fields=('answer',)
        model=Submissions

    # def __init__(self,*args,**kwargs):
    #     super().__init__(*args,**kwargs)
    #     self.fields['answer']='Upload your file'

class RegisterForm(forms.ModelForm):
    secret_code = forms.CharField(max_length=30)

    class Meta():
        fields=()
        model=RegUsers

class GradingForm(forms.ModelForm):
    feedback=forms.CharField(widget=forms.Textarea, required=False)
    marks=forms.IntegerField()

    class Meta():
        fields=('marks','feedback')
        model=Submissions

    def clean(self):
        cleaned_data = super().clean()

        if (cleaned_data['marks'] > self.instance.course.max_marks) or (cleaned_data['marks'] < 0):
            raise forms.ValidationError('Marks should be between 0 and %s.' % str(self.instance.course.max_marks))
        return cleaned_data

assignment_info/views.py
from django.shortcuts import render
from .forms import SubmissionForm,CourseForm,CreateCourseForm,RegisterForm,GradingForm
from django.contrib.auth import get_user_model
from .models import Course,Submissions,Cname,RegUsers
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView,CreateView,DetailView,UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.shortcuts import get_object_or_404
import datetime
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.core.exceptions import PermissionDenied
from datetime import date
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import redirect

    
@login_required
def SubmissionFormView(request,pk=None):
    course = get_object_or_404(Course, pk=pk)
    instance = Submissions.objects.filter(course=course, user=request.user).first()

    submitted = (instance is not None)
    current_time=datetime.datetime.now()

    if request.method=="POST":
        sub_form = SubmissionForm(request.POST or None, request.FILES or None, instance=instance)
        if sub_form.is_valid():
            form=sub_form.save(commit=False)
            form.user=request.user
            form.course=course
            form.submitted_at=datetime.datetime.now()
            # if 'answer' in request.FILES:
            if 'answer' in request.FILES:
                form.answer=request.FILES['answer']
            form.save()
            submitted=True
    else:
        sub_form=SubmissionForm()

    return render(request,template_name='submit.html',context={
        'form':sub_form,
        'submitted':submitted,
        'course':course,
        'current_time':current_time,
        'superuser':request.user.is_superuser
    })

@login_required
def RegisterFormView(request,pk=None):
    course = get_object_or_404(Cname, pk=pk)
    instance = RegUsers.objects.filter(course=course, user=request.user).first()
    wrong_key = 0

    submitted = (instance is not None)

    if request.method=="POST":
        sub_form = RegisterForm(request.POST or None, request.FILES or None, instance=instance)
        if sub_form.is_valid():
            key_received = sub_form.cleaned_data["secret_code"]
            if key_received == course.secret_code:
                form=sub_form.save(commit=False)
                form.user=request.user
                form.course=course
                # if 'answer' in request.FILES:
                form.save()
                submitted=True

                return redirect('assignments:available')
            else:
                # sub_form=RegisterForm()
                wrong_key = 1
    else:
        sub_form=RegisterForm()

    return render(request,template_name='register_course.html',context={
        'form':sub_form,
        'submitted':submitted,
        'course':course,
        'superuser':request.user.is_superuser,
        'wrong_key':wrong_key
    })

@login_required
def CourseView(request):
    if request.user.is_superuser:
        created=False
        if request.method=='POST':
            course_form=CourseForm(request.user, request.POST, request.FILES)

            if course_form.is_valid():
                form=course_form.save(commit=False)
                if 'question_file' in request.FILES:
                    form.question_file=request.FILES['question_file']
                form.save()
                created=True
                sub_str = form.code.code + ' ' + form.name
                content_str = 'An assignment has been created for ' + form.code.code + 'course.\n' + 'Details:\nAssignment name: ' + form.name + '\n'  + 'Assignment deadline: ' + str(form.deadline_date) + ' , ' + str(form.deadline_time) + '\n'


                # get the email id of all registered users
                reg_users = RegUsers.objects.filter(course=form.code)
                email_str = []
                for user in reg_users:
                    email_str.append(user.user.email)
                # print(email_str)
                send_mail(sub_str, content_str, 'submissionPortalProject@gmail.com',email_str, fail_silently=False)
                # form.deadline_date=form.d_date
            else:
                print(course_form.errors)
        else:
            course_form=CourseForm(request.user)
        return render(request,'course_form.html',context={
            'form':course_form,
            'created':created
        })
    else:
        raise PermissionDenied()

@login_required
def CreateCourseView(request):
    if request.user.is_superuser:
        created=False
        course_code = 'Code ***'
        if request.method=='POST':
            course_form=CreateCourseForm(request.POST,request.FILES)
            if course_form.is_valid():
                form=course_form.save(commit=False)
                form.save()
                created=True
                course_code = form.code
                reg_user = RegUsers(user=request.user, course=form)
                reg_user.save()
            else:
                print(course_form.errors)
        else:
            course_form=CreateCourseForm()
        return render(request,'create_course.html',context={
            'form':course_form,
            'created':created,
            'course_code': course_code
        })
    else:
        raise PermissionDenied()
    
@login_required
def AssigmentList(request):
    course_list=Course.objects.all()
    temp = RegUsers.objects.filter(user=request.user)
    # course_list = []
    # for i in temp:
    #     course_list.append(Course.objects.filter(code=i.course.code))
    
    # print(course_list[0].pk)

    final_list = []

    for i in course_list:
        for j in temp:
            if i.code.code == j.course.code:
                final_list.append(i)
                break
       
    return render(request, 'course_list.html', context={'course_list':final_list})

@login_required
def Assignments_list(request,pk):
    if(request.user.is_superuser):
        if(request.method == 'POST'):
            # print("helo")
            sub = get_object_or_404(Submissions,pk=pk)
            course=get_object_or_404(Course,pk=sub.course.pk)
            sub.marks=request.POST.get('gde')
            sub.save()
            send_mail('Subject here', 'Here is the message marks = ' + sub.marks, 'submissionPortalProject@gmail.com',['arpankhanna70@gmail.com'], fail_silently=False)
            # print(request.POST.get('gde'))
            return render(request,'assigments_list.html',context={'course':course})
        else:
            course=get_object_or_404(Course,pk=pk)
            return render(request,'assigments_list.html',context={'course':course})
    else:
        raise PermissionDenied()

class SuperUserRequiredMixin(LoginRequiredMixin, UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_superuser


def SubmissionListView(request):
    registered_courses = [reg.course for reg in RegUsers.objects.filter(user=request.user)]
    context = {'course_list': [course for course in Course.objects.all() if course.code in registered_courses]}

    return render(request, 'submissions_list.html', context=context)


@login_required
def GradingPage(request,pk):
    if(request.user.is_superuser):
        sub = get_object_or_404(Submissions,pk=pk)
        created=False
        if request.method=="POST":
            sub_form = GradingForm(request.POST or None, request.FILES or None, instance=sub)
            if sub_form.is_valid():
                form=sub_form.save(commit=False)
                sub.checked_by=request.user.username
                sub.marks=form.marks
                sub.feedback=form.feedback
                sub.save()
                created=True

                sub_str = sub.course.code.code + ' ' + sub.course.name + ' ' + 'marks'
                body_str = 'Your assignment for ' + sub.course.code.code + ' ' + sub.course.name + ' has been marked.\n' +'marks: ' + str(sub.marks) + '\n' + 'Feedback: ' + sub.feedback + '\n' + 'Checked by: ' + sub.checked_by + '\n'

                email_id  = []
                email_id.append(sub.user.email)

                send_mail(sub_str, body_str, 'submissionPortalProject@gmail.com',email_id, fail_silently=False)
                
                return redirect('/course/assignment/' + str(sub.course.pk))

        else:
            if (sub.marks >= 0):
                sub_form=GradingForm(instance=sub)
            else:
                sub_form=GradingForm()

        return render(request,template_name='grading_page.html',context={
            'form':sub_form,
            'submission':sub,
            'created':created
        })

    else:
        raise PermissionDenied()

@login_required
def deletingAssign(request,pk):
    course=get_object_or_404(Course,pk=pk)
    course.delete()
    return render(request,'deleteassign.html')

@login_required
def AvailableListView(request):
    course_list = Cname.objects.all()

    temp = RegUsers.objects.filter(user=request.user)
    c_registerd = []
    for i in temp:
        c_registerd.append(Cname.objects.get(code=i.course))

    print(c_registerd)
    return render(request,'available_course.html',context={'course_list':course_list,'c_registerd':c_registerd})

@login_required
def DeregisterCourse(request,pk):
    course_code = Cname.objects.filter(pk = pk)
    course = RegUsers.objects.filter(user = request.user,course = course_code[0])
    course.delete()
    return redirect('assignments:available')

assignment_info/templates/assigments_list.html
{% extends "base.html" %}

{% block content %}

<br><h2 class='display 4'>{{ course.name }}</h2><br>
<table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Roll No.</th>
        <th scope="col">Name</th>
        <th scope="col">Submitted at</th>
        <th scope="col">File </th>
        <th scope="col">Marks </th>
      </tr>
    </thead>
    <tbody>
        {% for i in course.submission.all %}
      <tr>
        <th scope="row">{{ i.user.last_name }}</th>
        <td>{{ i.user.first_name}}</td>
        <td>{{i.submitted_at}}</td>
        <td><a href='{{i.answer.url }}' class='btn btn-danger'download>Download</a></td>

        {% if i.marks == -1 %}
        <td><a href="{% url 'assignments:grading_page' pk=i.pk %}"> Grade Now</a></td>
        {% else %}
        <td><a href="{% url 'assignments:grading_page' pk=i.pk %}" style = 'color:red'> {{ i.marks }} </a></td>
        {% endif %}
        
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

assignment_info/templates/available_course.html
{% extends "base.html" %}
{% block content %}
<br>
<h2>Offered Courses</h2><br>
<table class="table">
    <thead>
      <tr>
        <th scope="col">Courses Code</th>
        <th scope="col">Courses Name</th>
        <th scope="col">Status</th>
      </tr>
    </thead>
    <tbody>
        {% for c in course_list %}
        {% if c in c_registerd %}
        <tr>
          <td>{{ c.code }}</td>
          <td>{{ c.course_name }}</td>
          <td><a href="{% url 'assignments:deregister_course' pk=c.pk %}" class='btn btn-danger' >Deregister </a></td>
          </tr>
        {% else %}
        <tr>
        <td>{{ c.code }}</td>
        <td>{{ c.course_name }}</td>
        <td><a href="{% url 'assignments:register_course' pk=c.pk %}" class='btn btn-primary' >Register Now </a></td>
        </tr>
        {% endif %}
        {% endfor %}
    </tbody>
  </table>
{% endblock %}

assignment_info/templates/course_form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
  {% if created %}
  <br>
  <h2>Assignment has been created</h2><br>
  <a href="{% url 'assignments:list' %}" class="btn btn-primary">Go back to the assignments list page</a>
  {% else %}
  <br><h2>Create Assignment</h2><br>
  <form class="" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" name="" value="Create" class="btn btn-warning">
  </form>
  <br>
  {% endif %}
{% endblock %}

assignment_info/templates/course_list.html
{% extends "base.html" %}
{% block content %}
<br><h2>Assignments</h2><br>
<table class="table">
    <thead>
      <tr>
        <th scope="col">Course Code</th>
        <th scope="col">Assignment</th>
        <th scope="col">Deadline</th>
        <th scope="col">        </th>
      </tr>
    </thead>
    <tbody>
        {% for c in course_list %}
        <tr>
        <td>{{ c.code }}</td>
        <td>{{ c.name }}</td>
        <td>{{ c.deadline_date }} | {{ c.deadline_time}}</td>
        <td><a href="{% url 'assignments:submit' pk=c.pk %}" class='btn btn-primary'> View </a></td>
        </tr>
        {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

assignment_info/templates/create_course.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
  {% if created %}
  <br>
  <h2>Course {{course_code}} has been created and the user has been automatically added to the course</h2><br>
  <a href="{% url 'index' %}" class="btn btn-primary">Go back to the home page</a>
  {% else %}
  <br>
  <h2>Create Course</h2>
  <form class="" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" name="" value="Create" class="btn btn-warning">
  </form>
  <br>
  {% endif %}
{% endblock %}

assignment_info/templates/deleteassign.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<br>
<h2>Assignment has been deleted.</h2>
<br>


<!-- go back to the homepage with a button -->
<a href="{% url 'assignments:list' %}" class="btn btn-primary">Go back to the assigments list page</a>
<!-- <a href="{% url 'assignments:list' %}">Go back to the homepage</a> -->

{% endblock %}

assignment_info/templates/grading_page.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}

<br>
<h3>{{ submission.course }}</h3><br>
<h5>Name:  {{submission.user.first_name}}</h4>
<h5>Roll No.: {{submission.user.last_name}}</h5>
<h5>Max. Marks: {{ submission.course.max_marks }}</h5><br>

<form class="" enctype="multipart/form-data" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" name="" value="Grade" class="btn btn-primary">
</form>

{% endblock %}

assignment_info/templates/register_course.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<br>
{% if wrong_key %}
<h3> Wrong key entered.</h3>
{% endif %}

<h3>Register for the course {{course.code}}</h3>
<br>
<form enctype="multipart/form-data" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <br>
  <input type="submit" name="" value="Submit" class='btn btn-primary'>
</form>

{% endblock %}

assignment_info/templates/submissions_list.html
{% extends "base.html" %}
{% block content %}
<br><h2>Assignments</h2><br>
<table class="table">
    <thead>
      <tr>
        <th scope="col">Course Code</th>
        <th scope="col">Assignment</th>
        <th scope="col">Deadline</th>
        <th scope="col">        </th>
      </tr>
    </thead>
    <tbody>
        {% for c in course_list %}
        <tr>
        <td>{{ c.code }}</td>
        <td>{{ c.name }}</td>
        <td>{{ c.deadline_date }} | {{ c.deadline_time}}</td>
        <td><a href="{% url 'assignments:assignment_list' pk=c.pk %}" class='btn btn-primary' >View Submissions </a></td>
        </tr>
        {% endfor %}
    </tbody>
  </table>
{% endblock %}

assignment_info/templates/submit.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<br>
{% if superuser == 0 %}
      {% if current_time.date < course.deadline_date %}
            <div class="card">
              <div class="card-header">
                <h3>{{ course.name }}</h3>
              </div>
                <div class="card-body">
                  <p class="card-text">Question: <br>{{ course.question }}</p>
                  <p>Attachments:<br><a href="{{course.question_file.url}}" download>{{course.question_file.name}}</a></p>
                  <p>Deadline: {{ c.deadline_date }} | {{ c.deadline_time}} </p>
                  <form enctype="multipart/form-data" method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <input type="submit" name="" value="Submit" class='btn btn-primary'>
                  </form>
                </div>
              </div>
      {% else %}
          {% if current_time.date == course.deadline_date %}
            {% if current_time.time < course.deadline_time %}
                <div class="card">
                <div class="card-header">
                  <h3>{{ course.name }}</h3>
                </div>
                  <div class="card-body">
                    <p class="card-text">Question: <br>{{ course.question }}</p>
                    <p>Attachments:<br><a href="{{course.question_file.url}}" download>{{course.question_file.name}}</a></p>
                    <form enctype="multipart/form-data" method="post">
                      {% csrf_token %}
                      {% bootstrap_form form %}
                      <input type="submit" name="" value="Submit" class='btn btn-primary'>
                    </form>
                  </div>
                </div>
            {% else %}
              <div class="card">
                <div class="card-header">
                  <h3>{{ course.name }}</h3>
                </div>
                  <div class="card-body">
                    <p class="card-text">Question: <br>{{ course.question }}</p>
                    <p>Attachments:<br><a href="{{course.question_file.url}}" download>{{course.question_file.name}}</a></p>
                  </div>
                </div>
              {% endif %}

          {% else %}
              <div class="card">
                <div class="card-header">
                  <h3>{{ course.name }}</h3>
                </div>
                  <div class="card-body">
                    <p class="card-text">Question: <br>{{ course.question }}</p>
                    <p>Attachments:<br><a href="{{course.question_file.url}}" download>{{course.question_file.name}}</a></p>
                  </div>
                </div>
          {% endif %}

        {% endif %}

        {% if submitted %}
        <br>
        <div class="card">
          <div class="card-header">
            <h3>Submission</h3>
          </div>
          <div class="card-body">
              {% for i in course.submission.all %}
                {% if i.user.username == user.get_username %}
                  {%if i.marks == -1 %}
                    <p>Submission: <a href="{{ i.answer.url }}" download >{{i.answer.name}}</a></p>
                    <p>Not Graded Yet</p>
                  {% else %}
                    <p>Submission: <a href="{{ i.answer.url }}" download >{{i.answer.name}}</a></p>
                    <p>Marks: {{i.marks}}</p>
                    <p>Feedback: {{i.feedback}}</p>
                    <p>Checked by: {{i.checked_by}}</p>
                  {% endif %}
                {% endif %}
              {% endfor %}
          </div>
        </div>
        {% endif %}

{% else %}
      <div class="card">
        <div class="card-header">
          <h3>{{ course.name }}</h3>
        </div>
          <div class="card-body">
            <p class="card-text">Question: <br>{{ course.question }}</p>
            <p>Attachments:<br><a href="{{course.question_file.url}}" download>{{course.question_file.name}}</a></p>
          </div>
        </div>
      <br><br>
      <div class="card">
        <div class="card-header">
          <h3>Delete</h3>
        </div>
        <div class="card-body">
          <p class="card-text" style = "color:red">Warning: Deleting this assignment will delete all the submissions and grades. This is an irreversible action.</p>
          <form action="{% url 'assignments:deleteassign' course.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" name="" value="Delete" class='btn btn-danger'>
          </form>
        </div>
      </div>
{% endif %}
{% endblock %}

assignment_info/templates/submit_update.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
  {% if current_time.date >= course.deadline_date %}
    {% if current_time.time > course.deadline_time %}
      <h3>You cannot submit this assignment anymore.</h3>
    {% else %}
      {% if submitted %}
        <h2>You have successfully submitted your assignment.</h2>
      {% else %}
        <h1>Update: </h2>
        <h4>Question: </h4>
        <p>{{course.question}}</p>
        <form enctype="multipart/form-data" method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          <input type="submit" name="" value="Submit" class='btn btn-primary'>
        </form>
      {%endif%}
    {% endif %}
    {% else %}
    {% if submitted %}
      <h2>You have successfully submitted your assignment.</h2>
    {% else %}
      <h1>Submit your assignment</h2>
      <h4>Question:</h4>
      <p>{{course.question}}</p>
      <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" name="" value="Submit" class='btn btn-primary'>
      </form>
    {%endif%}
  {% endif %}

{% endblock %}